server:
  port: 8080

spring:
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/employee_base?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true