server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: Zabava532600
    url: jdbc:postgresql://localhost:5432/employee_base?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

security-settings:
  users:
    - login: admin
      password: admin
    - login: user1
      password: user1
    - login: user2
      password: user2
